
package com.dachen.health.user.service.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BarCodeService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://202.105.134.87/WcfServices/CMS.Common.UserValidation.Services/BarCodeService.svc?wsdl")
public class BarCodeService
    extends Service
{

    private final static URL BARCODESERVICE_WSDL_LOCATION;
    private final static WebServiceException BARCODESERVICE_EXCEPTION;
    private final static QName BARCODESERVICE_QNAME = new QName("http://tempuri.org/", "BarCodeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://202.105.134.87/WcfServices/CMS.Common.UserValidation.Services/BarCodeService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BARCODESERVICE_WSDL_LOCATION = url;
        BARCODESERVICE_EXCEPTION = e;
    }

    public BarCodeService() {
        super(__getWsdlLocation(), BARCODESERVICE_QNAME);
    }

    public BarCodeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BARCODESERVICE_QNAME, features);
    }

    public BarCodeService(URL wsdlLocation) {
        super(wsdlLocation, BARCODESERVICE_QNAME);
    }

    public BarCodeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BARCODESERVICE_QNAME, features);
    }

    public BarCodeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BarCodeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBarCodeService
     */
    @WebEndpoint(name = "BasicHttpBinding_IBarCodeService")
    public IBarCodeService getBasicHttpBindingIBarCodeService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IBarCodeService"), IBarCodeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBarCodeService
     */
    @WebEndpoint(name = "BasicHttpBinding_IBarCodeService")
    public IBarCodeService getBasicHttpBindingIBarCodeService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IBarCodeService"), IBarCodeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BARCODESERVICE_EXCEPTION!= null) {
            throw BARCODESERVICE_EXCEPTION;
        }
        return BARCODESERVICE_WSDL_LOCATION;
    }

}
