
package com.dachen.health.user.service.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBarCodeService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBarCodeService {


    /**
     * 
     * @param stfName
     * @param latitude
     * @param stfCode
     * @param barCode
     * @param longitude
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBarCodeInfo", action = "http://tempuri.org/IBarCodeService/GetBarCodeInfo")
    @WebResult(name = "GetBarCodeInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBarCodeInfo", targetNamespace = "http://tempuri.org/", className = "main.java.wskz.client.GetBarCodeInfo")
    @ResponseWrapper(localName = "GetBarCodeInfoResponse", targetNamespace = "http://tempuri.org/", className = "main.java.wskz.client.GetBarCodeInfoResponse")
    public String getBarCodeInfo(
        @WebParam(name = "barCode", targetNamespace = "http://tempuri.org/")
        String barCode,
        @WebParam(name = "longitude", targetNamespace = "http://tempuri.org/")
        String longitude,
        @WebParam(name = "latitude", targetNamespace = "http://tempuri.org/")
        String latitude,
        @WebParam(name = "stfName", targetNamespace = "http://tempuri.org/")
        String stfName,
        @WebParam(name = "stfCode", targetNamespace = "http://tempuri.org/")
        String stfCode);

}
